import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { satoshi } from "./fonts";
import { SessionProvider } from "@/lib/providers/SessionProvider";
import { getUserFromCookie } from "@/lib/api/auth";
import Providers from "./auth/Providers";
import { cn } from "@/lib/utils";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUserFromCookie();
  return (
    <html lang="en" className={cn("font-sans", satoshi.variable)}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <SessionProvider user={user}>{children}</SessionProvider>
        </Providers>
      </body>
    </html>
  );
}
